name: Pull Request workflow

on:
  pull_request:
      types: [opened, synchronize]
      branches: [ dev ]

        
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
    steps:
      - name: Checkout Source Branch  
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Run Unit Tests
        run: dotnet test

